[platformio]
extra_configs = ../platformio.ini

[env:client]
extends = common_esp32c3
build_flags =
    ${common_esp32c3.build_flags}
    -D ROLE_CLIENT
    -D DRIVE_INTERVAL_MS=33
    -D DEVICE_ID=1  ; override per device at flash time
