; platformio.ini  (root — workspace only, no env here)
[platformio]
projects_dir = server, car, client

[common_esp32c3]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -D ESPNOW_CHANNEL=1
    -D ROUNDS_TO_WIN=2
lib_extra_dirs = ../lib
