[platformio]
extra_configs = ../platformio.ini

[env:server]
extends = common_esp32c3
lib_ldf_mode = chain+
lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
    bblanchon/ArduinoJson @ ^7.0.0
build_flags =
    ${common_esp32c3.build_flags}
    -D ROLE_SERVER

[env:native_test]
platform = native
test_framework = unity
build_flags =
    -std=gnu++17
    -I../lib/blahaj_common
    -Isrc
    -D ROUNDS_TO_WIN=2
lib_extra_dirs = ../lib
build_src_filter = -<*> +<game_engine.cpp>
test_build_src = yes
