[platformio]
extra_configs = ../platformio.ini

[env:referee]
extends = common_esp32
lib_ldf_mode = chain+
lib_extra_dirs = ../lib
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    paulstoffregen/XPT2046_Touchscreen
    lvgl/lvgl @ ^9.5.0
build_flags =
    ${common_esp32.build_flags}
    -D ROLE_REFEREE
    -D ESPNOW_CHANNEL=6
    -D LV_CONF_INCLUDE_SIMPLE=1
    -Iinclude
    ; CYD (ESP32-2432S028) display wiring for TFT_eSPI
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=1
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=55000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
